//! README Markdown regeneration for the relay catalog.
//!
//! The generator only edits the block between [`README_START_MARKER`] and
//! [`README_END_MARKER`]. The rest of the README is hand-maintained (project
//! intro, contribution notes, badges, etc.).
//!
//! The implementation intentionally uses `push_str(&format!(...))` rather than
//! `write!` + `std::fmt::Write`. The allocations are one-shot per line and the
//! resulting code is noticeably clearer than threading `fmt::Result` through
//! every helper.

#![allow(
    clippy::format_push_string,
    reason = "render is a one-shot template; extra allocations are not a bottleneck"
)]

use std::{fs, path::Path};

use anyhow::{Context, Result, anyhow};
use chrono::Utc;

use crate::{
    DEAD_FAILURE_THRESHOLD, README_END_MARKER, README_START_MARKER, WARN_FAILURE_THRESHOLD,
    health::status_icon,
    model::{Dataset, HealthEntry, HealthReport, Relay},
};

/// Rewrite `path` so that the `RELAYS:START` / `RELAYS:END` block contains a
/// freshly rendered catalog. The function is idempotent when the dataset has
/// not changed.
///
/// # Errors
///
/// Returns an error when the README cannot be read or written, or when either
/// marker is missing or out of order.
pub fn update_readme(path: &Path, dataset: &Dataset, health: &HealthReport) -> Result<()> {
    let original =
        fs::read_to_string(path).with_context(|| format!("failed to read {}", path.display()))?;

    let start = original
        .find(README_START_MARKER)
        .ok_or_else(|| anyhow!("missing {README_START_MARKER} marker in {}", path.display()))?;
    let end = original
        .find(README_END_MARKER)
        .ok_or_else(|| anyhow!("missing {README_END_MARKER} marker in {}", path.display()))?;
    if end <= start {
        return Err(anyhow!(
            "{README_START_MARKER} appears after {README_END_MARKER} in {}",
            path.display()
        ));
    }

    let rendered = render_section(dataset, health);
    let start_end = start.saturating_add(README_START_MARKER.len());
    let mut new_text = String::with_capacity(original.len().saturating_add(rendered.len()));
    new_text.push_str(&original[..start_end]);
    new_text.push('\n');
    new_text.push_str(&rendered);
    new_text.push_str(&original[end..]);

    if new_text != original {
        fs::write(path, new_text).with_context(|| format!("failed to write {}", path.display()))?;
    }
    Ok(())
}

fn render_section(dataset: &Dataset, health: &HealthReport) -> String {
    let total = dataset.relays.len();
    let healthy = dataset
        .relays
        .iter()
        .filter(|r| {
            health
                .entries
                .get(r.url.as_str())
                .is_some_and(HealthEntry::is_online)
        })
        .count();

    let mut out = String::new();
    out.push_str("<!-- The content between RELAYS:START and RELAYS:END is\n");
    out.push_str("     auto-generated by `relays build`. Do not edit by hand. -->\n\n");
    out.push_str(&format!(
        "> Catalog last generated at **{}** — **{total}** relays tracked, **{healthy}** currently healthy.\n\n",
        Utc::now().format("%Y-%m-%d %H:%M:%S UTC"),
    ));
    out.push_str(&format!(
        "**Legend**: ✅ healthy · ❔ never probed · ⚠️ {WARN_FAILURE_THRESHOLD} consecutive failures · 💀 ≥ {DEAD_FAILURE_THRESHOLD} consecutive failures (candidate for removal)\n\n",
    ));

    for collection in &dataset.collections {
        let relays: Vec<&Relay> = dataset
            .relays
            .iter()
            .filter(|r| r.collections.iter().any(|c| c == &collection.id))
            .collect();
        if relays.is_empty() {
            continue;
        }
        out.push_str(&format!("### {}\n\n", collection.name));
        if !collection.description.is_empty() {
            out.push_str(&collection.description);
            out.push_str("\n\n");
        }
        for relay in relays {
            render_relay_line(&mut out, relay, health);
        }
        out.push('\n');
    }
    out
}

fn render_relay_line(out: &mut String, relay: &Relay, health: &HealthReport) {
    let icon = status_icon(health.entries.get(relay.url.as_str()));
    out.push_str(&format!("- {icon} `{}`", relay.url.as_str()));
    if let Some(name) = &relay.name
        && !name.is_empty()
    {
        out.push_str(&format!(" — **{name}**"));
    }
    if let Some(country) = &relay.country {
        out.push_str(&format!(" · {country}"));
    }
    if relay.paid == Some(true) {
        out.push_str(" · 💰");
    }
    if let Some(desc) = &relay.description
        && !desc.is_empty()
    {
        out.push_str(&format!(" — {desc}"));
    }
    out.push('\n');
}
