//! README Markdown regeneration for the relay catalog.
//!
//! The generator only edits the block between [`README_START_MARKER`] and
//! [`README_END_MARKER`]. The rest of the README is hand-maintained (project
//! intro, contribution notes, badges, etc.).
//!
//! The implementation intentionally uses `push_str(&format!(...))` rather than
//! `write!` + `std::fmt::Write`. The allocations are one-shot per line and the
//! resulting code is noticeably clearer than threading `fmt::Result` through
//! every helper.
//!
//! Writes are **content-addressed**: the generated-at line is compared
//! separately from the payload body so a file is only rewritten when the
//! underlying catalog or health data actually changed, preventing hourly CI
//! runs from producing noise commits.

#![allow(
    clippy::format_push_string,
    reason = "render is a one-shot template; extra allocations are not a bottleneck"
)]

use std::{fs, path::Path};

use anyhow::{Context, Result, anyhow};
use chrono::Utc;

use crate::{
    README_END_MARKER, README_START_MARKER,
    model::{Dataset, Network, Relay},
};

/// Prefix identifying the wall-clock timestamp line. The line is excluded
/// from content comparisons so a fresh CI run with unchanged data does not
/// trigger a rewrite.
const TIMESTAMP_LINE_PREFIX: &str = "> Catalog last generated at";

/// Rewrite `path` so that the `RELAYS:START` / `RELAYS:END` block contains a
/// freshly rendered catalog.
///
/// The function is idempotent when the dataset has not changed: if the body
/// (every line except the generated-at stamp) is byte-for-byte identical to
/// the existing block, the file is left untouched.
///
/// # Errors
///
/// Returns an error when the README cannot be read or written, or when either
/// marker is missing or out of order.
pub fn update_readme(path: &Path, dataset: &Dataset) -> Result<()> {
    let original =
        fs::read_to_string(path).with_context(|| format!("failed to read {}", path.display()))?;

    let start = original
        .find(README_START_MARKER)
        .ok_or_else(|| anyhow!("missing {README_START_MARKER} marker in {}", path.display()))?;
    let end = original
        .find(README_END_MARKER)
        .ok_or_else(|| anyhow!("missing {README_END_MARKER} marker in {}", path.display()))?;
    if end <= start {
        return Err(anyhow!(
            "{README_START_MARKER} appears after {README_END_MARKER} in {}",
            path.display()
        ));
    }

    let start_end = start.saturating_add(README_START_MARKER.len());
    let existing_section = &original[start_end..end];
    let new_section = render_section(dataset);

    if strip_timestamp(existing_section) == strip_timestamp(&new_section) {
        return Ok(());
    }

    let mut new_text = String::with_capacity(original.len().saturating_add(new_section.len()));
    new_text.push_str(&original[..start_end]);
    new_text.push_str(&new_section);
    new_text.push_str(&original[end..]);

    fs::write(path, new_text).with_context(|| format!("failed to write {}", path.display()))?;
    Ok(())
}

/// Render the full section body (including the volatile timestamp line).
///
/// The catalog is rendered without per-relay health: live status is published
/// separately to the JSON API and a shields.io badge, so this block only
/// changes when the curated catalog itself does.
fn render_section(dataset: &Dataset) -> String {
    let total = dataset.relays.len();

    let mut out = String::new();
    out.push('\n');
    out.push_str("<!-- The content between RELAYS:START and RELAYS:END is\n");
    out.push_str("     auto-generated by `relays build`. Do not edit by hand. -->\n\n");
    out.push_str(&format!(
        "{TIMESTAMP_LINE_PREFIX} **{}**.\n",
        Utc::now().format("%Y-%m-%d %H:%M:%S UTC"),
    ));
    out.push_str(&format!(
        "> **{total}** relays tracked · live health \
         [![healthy](https://img.shields.io/endpoint?url=https%3A%2F%2Frelays.meowl.social%2Fbadge.json)](https://relays.meowl.social/) \
         · full machine-readable status in [`relays.json`](https://relays.meowl.social/relays.json).\n\n",
    ));

    for collection in &dataset.collections {
        let relays: Vec<&Relay> = dataset
            .relays
            .iter()
            .filter(|r| r.collections.iter().any(|c| c == &collection.id))
            .collect();
        if relays.is_empty() {
            continue;
        }
        out.push_str(&format!("### {}\n\n", collection.name));
        if !collection.description.is_empty() {
            out.push_str(&collection.description);
            out.push_str("\n\n");
        }
        for relay in relays {
            render_relay_line(&mut out, relay);
        }
        out.push('\n');
    }
    out
}

fn render_relay_line(out: &mut String, relay: &Relay) {
    out.push_str(&format!("- `{}`", relay.url.as_str()));
    if let Some(name) = &relay.name
        && !name.is_empty()
    {
        out.push_str(&format!(" — **{name}**"));
    }
    if let Some(country) = &relay.country {
        out.push_str(&format!(" · {country}"));
    } else if relay.effective_network() != Network::Clearnet {
        out.push_str(&format!(" · {}", relay.effective_network().as_str()));
    }
    if relay.is_paid() {
        out.push_str(" · 💰");
    }
    if let Some(desc) = &relay.description
        && !desc.is_empty()
    {
        out.push_str(&format!(" — {desc}"));
    }
    out.push('\n');
}

/// Return `text` with every line starting with [`TIMESTAMP_LINE_PREFIX`]
/// removed. Used solely for equality comparisons, never for display output.
fn strip_timestamp(text: &str) -> String {
    text.lines()
        .filter(|line| !line.starts_with(TIMESTAMP_LINE_PREFIX))
        .collect::<Vec<_>>()
        .join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn strip_timestamp_removes_marked_lines_only() {
        let sample = "\
> Catalog last generated at **2026-05-02**.
> **3** relays tracked · **2** currently healthy.
### Featured
- ✅ `wss://a/`
";
        let stripped = strip_timestamp(sample);
        assert!(!stripped.contains("Catalog last generated"));
        assert!(stripped.contains("3** relays tracked"));
        assert!(stripped.contains("### Featured"));
        assert!(stripped.contains("wss://a/"));
    }

    #[test]
    fn strip_timestamp_ignores_lines_without_prefix() {
        let sample = "> Some other quote\n> **5** relays tracked.\n";
        let stripped = strip_timestamp(sample);
        assert_eq!(stripped, "> Some other quote\n> **5** relays tracked.");
    }

    #[test]
    fn strip_timestamp_is_stable_under_timestamp_change() {
        let a = "> Catalog last generated at **2026-01-01 00:00:00 UTC**.\n> **3** tracked.\n";
        let b = "> Catalog last generated at **2026-05-02 09:15:36 UTC**.\n> **3** tracked.\n";
        assert_eq!(strip_timestamp(a), strip_timestamp(b));
    }

    #[test]
    fn strip_timestamp_detects_body_change() {
        let a = "> Catalog last generated at **T**.\n> **3** tracked.\n";
        let b = "> Catalog last generated at **T**.\n> **4** tracked.\n";
        assert_ne!(strip_timestamp(a), strip_timestamp(b));
    }
}
